- README.md
- package-lock.json
- package.json
- src/cli-main.ts
- src/service/edgeworkers-client-manager.ts
- src/utils/cli-utils.ts
- src/utils/env-utils.ts
Updates to support outputting to json file at provided local path, or defaults to <CLI_CACHE_PATH>/edgeworkers-cli/edgeworkers/
> CLI: Support --json flag to output json response opposed to only displaying it [3428]

- README.md
- cli.json
- package-lock.json
- package.json
- src/cli-main.ts
Adding EdgeWorkers Auth Token generation that can be used in conjunction with debug headers.
> Adding Auth Token generation.

- README.md
- cli.json
- package-lock.json
- package.json
- src/cli-main.ts
https://track.akamai.com/jira/browse/EW-5763
This reuses the cryptoJS library to generate random secret token
> EW-5763 Adding command to generate random secret token

- docs/edgekv_cli.md
Adding known issues to read me doc
> Adding known issues to readme

- README.md
- cli.json
- docs/edgekv_cli.md
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgekv/ekv-error.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-response.ts
- src/edgekv/http-error-message.ts
- src/edgeworkers/ew-service.ts
Download bundle was failing when account key was provided. The account key was getting reset specifically for the download bundle command.
[EW-6997](https://track.akamai.com/jira/browse/EW-6697)
> EW-6697 - Download bundle fix for account key

- README.md
- cli.json
- docs/edgekv_cli.md
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-error.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-helper.ts
- src/edgekv/ekv-response.ts
- src/edgekv/ekv-service.ts
- src/edgekv/http-error-message.ts
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-error.ts
- src/edgeworkers/ew-handler.ts
- src/edgeworkers/ew-service.ts
- src/utils/http-error-message.ts
Updates to existing API:
- Create new edgeworker
- Edit an EdgeWorker ID
- Fetch EdgeWorker IDs
New Endpoints
- Clone an EdgeWorker ID
- List Contract IDs for Resource Tiers
- List Resource Tiers for a specific Contract ID
- Fetch the Resource Tier for a specific EdgeWorker ID
> Resource tier support for CLI 

- cli.json
- docs/edgekv_cli.md
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-helper.ts
- src/edgekv/ekv-response.ts
- src/edgekv/ekv-service.ts
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-error.ts
- src/edgeworkers/ew-handler.ts
- src/utils/http-error-message.ts
[Support for listing expired tokens](https://track.akamai.com/jira/browse/EDB-1074)
[Support for retrieving namespace details](https://track.akamai.com/jira/browse/EDB-1077)
[Support for new namespace attributes](https://track.akamai.com/jira/browse/EDB-1078)
[Bug fix for reading empty value](https://track.akamai.com/jira/browse/EDB-1046)
[Enforce a retention period for namespace creation](https://track.akamai.com/jira/browse/EDB-912)
[Update EKV CLI to handle new EKV API input/output JSON](https://track.akamai.com/jira/browse/EDB-1075)
> Edgekv CLI updates

- README.md
- cli.json
- package-lock.json
- package.json
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-handler.ts
- src/edgeworkers/ew-service.ts
Providing optional resource tier and contract id as input for automation purposes
> Fix for automation

- cli.json
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgeworkers/ew-handler.ts
- src/edgeworkers/ew-service.ts
- src/utils/cli-utils.ts
Updated units:
```
------------------------------------------
--- ResourceTier 200 - Dynamic Compute ---
------------------------------------------
Maximum CPU time during initialization: 30 ms
Maximum wall time during initialization: 100 ms
Maximum memory usage per event handler: 1.5 MB
Maximum CPU time per event handler: 10 ms
Maximum wall time per event handler: 4 s
Maximum number of HTTP sub-requests allowed from a parent request: 1
Maximum number of HTTP sub-requests allowed in parallel per request: 1
Maximum wall time per HTTP sub-request: 1 s
Maximum response size per HTTP sub-request: 5 MB
Maximum memory usage for responseProvider: 2 MB
Maximum CPU time for responseProvider: 100 ms
Maximum wall time for responseProvider: 4 s
Maximum number of HTTP sub-requests allowed for …
```
> Updated resource tier units in output

- cli.json
- package-lock.json
- package.json
- src/utils/env-utils.ts
There are some unexpected build failures showing up -- to mitigate this I am reverting the edgegrid change I made last week, and can re-evaluate after we have better safety set up on our master branch
> Revert edgegrid change

- docs/edgekv_cli.md
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-service.ts
edgekv list items < environment > < nameSpace > < groupId > --maxItems <maxItems>
> add maxItems option to list items cmd

- src/edgeworkers/ew-error.ts
- src/edgeworkers/ew-handler.ts
> cli delete command with json option will download json successfully 

- .editorconfig
- .env.example
- .eslintrc.js
- .gitignore
- babel.config.js
- jest.config.js
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgeworkers/ew-service.ts
- src/utils/env-utils.ts
- tests/cli-httpRequest.test.ts
- tests/console_setup.js
- fixed error handling in cli-httpRequest
- added unit tests for the error handing fix
- updated typescript library version
- added jest library to implement unit tests
- added eslint library to check ts format
> EW-12363 Fix broken error handling in cli-httpRequest

- src/edgeworkers/client-manager.ts
- src/edgeworkers/ew-handler.ts
- Add a flag parameter to validateTarballLocally() function
- Format `client-manager.ts` and `client-manager.ts`
> EW-9054 Keep validate command error message formats consistent

- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-service.ts
- Add `groupId` parameter to updateNameSpace() function
- Format `ekv-cli-main.ts` and `ekv-handler.ts`
- The fix is [here](https://github.com/akamai/cli-edgeworkers/compare/develop...kyleli-akamai:cli-edgeworkers:bugfix/EW-13126?expand=1#diff-ad52197919319175e068cf2fafbfb2fe072d14714ba32e813fb7adaad9b682f9R142-R153)
> EW-13126 Fix EKV CLI modify namespace command

- docs/edgekv_cli.md
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/utils/cli-utils.ts
This PR updates the help text for create token and also automatically displays the help text if no options are provided to the command.
> EW-11937: Improve help text & automatically display help for EKV create token

- package-lock.json
- package.json
- src/edgekv/client-manager.ts
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-helper.ts
- src/edgekv/ekv-response.ts
- src/edgeworkers/client-manager.ts
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-handler.ts
- src/utils/cli-utils.ts
- src/utils/json-handler.ts
- tests/utils/json-handler.test.ts
This PR adds support for json and jsonout modes for all EKV commands.
The JSON output code has also been refactored and new unit tests have been added to test it.
> Feature/EW-13498: Support --json & --jsonout output flags for EKV commands

- package-lock.json
- package.json
- src/edgekv/ekv-cli-main.ts
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-handler.ts
EW-7436: Improve help output readability when using a narrow window
EW-14572: Display multiple validation errors when using the upload command
> Release v1.6.1

- src/edgekv/ekv-cli-main.ts
- src/edgeworkers/ew-cli-main.ts
> update year in copyright text

- .env.example
- README.md
- cli.json
- docs/edgekv_cli.md
- package-lock.json
- package.json
- src/edgekv/ekv-cli-main.ts
- src/edgeworkers/ew-cli-main.ts
- src/utils/config-utils.ts
- src/utils/constants.ts
- tests/utils/config-utils.test.ts
- Bump version to 1.7.1
- Added `ini` dependency
- Added `config-utils.ts` file
- Added unit tests
- Added config commands and pull default config properties on other commands
- Updated doc
> Provide default values to the CLI as a config file

- README.md
- cli.json
- package-lock.json
- package.json
- src/cli-httpRequest.ts
- src/edgekv/ekv-service.ts
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-handler.ts
- src/edgeworkers/ew-service.ts
- src/utils/constants.ts
- src/utils/http-error-message.ts
- tests/edgeworkers/ew-services.test.ts
```
macbook:~/ew/cli-edgeworkers $ ./akamai-edgeworkers  status 61488 --activeOnNetwork
---------------------------------------------------------------------------------------------------------------------------------------------------------
--- The following EdgeWorker Activations currently exist for account: B-C-BR0JK9, ewId: 61488, version: active, activationId: any, network: undefined ---
---------------------------------------------------------------------------------------------------------------------------------------------------------
┌─────────┬──────────────┬──────────┬──────────────┬──────────────┬────────────┬────────────────────────┐
│ (index) │ edgeWorkerId │ version  │ activationId │   network    │ createdBy  │      createdTime       │ …
```
> EW-13517:  support current active version requests to activation api

- cli.json
- src/cli-httpRequest.ts
- src/edgekv/ekv-cli-main.ts
- src/edgekv/ekv-handler.ts
- src/edgekv/ekv-helper.ts
- src/edgekv/ekv-metricFactory.ts
- src/edgekv/ekv-response.ts
- src/edgekv/ekv-service.ts
- tests/edgekv/ekv-services.test.ts
- Changes to Create Access Policy Token
- Changes to Retrieve Access Policy Token
- Changes to List Access Policy Tokens
- New Refresh Access Policy Token command
> EDB-2308: Token Workflow Enhancement updates

- cli.json
- package-lock.json
- package.json
- Add check to avoid building for `npm install --production`
> [EW-23495]: Update libs to support Node 18 

- README.md
- cli.json
- package-lock.json
- package.json
- src/edgeworkers/ew-cli-main.ts
- src/edgeworkers/ew-handler.ts
- src/edgeworkers/ew-service.ts
Add a new optional parameter auto-pin to the EdgeWorker Activation.
> EW-25227 Implement CLI changes for initial revision auto-pin
